
%%%%%%%%%%%%%%%%Figura
figure('Name','Amplificator Inversor',...
    'Units','normalized',...
    'Position',[0.05 0.05 0.8 0.85],...
    'NumberTitle','off');

set(gcf,'color','[0.96863     0.84706     0.65882]');

%%%%%%%%%%%%%%%%%%%%%% Meniu
fig=uimenu('Label','Proiect');
uimenu(fig,'Label','Documentatie','Callback','Documentatie');% Teorie
uimenu(fig,'Label','Prezentare','Callback','Prezentare');% Prezentare
uimenu(fig,'Label','Close','Callback','close',...
'Separator','on','Accelerator','Q');
   
%%%%%%%%%%%%%%%%%%%%%%Titlu
uicontrol('Style','text',...
          'Units','normalized',...
          'Position', [0.2 0.9 0.6 0.05],...
          'backgroundcolor', [0.70196   0.49804      0.4],...
          'foregroundcolor',[0.94 0.94 0.94 0.94],...
          'fontweight', 'bold',...
          'fontsize', 20,...
          'String','Amplificator cu AO - Inversor');
      
%%%%%%%%%%%%%%%%%Butoane
uicontrol('Style','pushbutton',...
          'Units','normalized',...
          'Position',[0.50 0.60 0.2 0.1],...
          'FontSize',12,...
          'String','Amplificator inversor',...
          'Callback','inversor_start');


uicontrol('Style','pushbutton',...
    'Units','normalized',...
    'Position',[0.05 0.60 0.2 0.1],...
    'FontSize',12,...
    'String','Documentatie',...
    'Callback','Documentatie;');


uicontrol('Style','pushbutton',...
    'Units','normalized',...
    'Position',[0.28 0.60 0.2 0.1],...
    'FontSize',12,...
    'String','Prezentare',...
    'Callback','Prezentare;');


uicontrol('Style','pushbutton',...
    'Units','normalized',...
    'Position',[0.73 0.60 0.2 0.1],...
    'FontSize',12,...
    'String','AO - Av reglabila',...
    'Callback','inversor_startr;');


     uicontrol('Style','text',...
          'Units','normalized',...
          'Position', [0.35 0.15 0.3 0.05],...
          'backgroundcolor', [0.96863     0.84706     0.65882],...
          'foregroundcolor',[0 0 0 0],...
          'fontsize',25,...
          'String','Nume:Alexi Mariuta');
      
      uicontrol('Style','text',...
          'Units','normalized',...
          'Position', [0.35 0.1 0.3 0.05],...
          'backgroundcolor', [0.96863     0.84706     0.65882],...
          'foregroundcolor',[0 0 0 0],...
          'fontsize',25,...
          'String','Seria: B');
      
       uicontrol('Style','text',...
          'Units','normalized',...
          'Position', [0.35 0.05 0.3 0.05],...
          'backgroundcolor', [0.96863     0.84706     0.65882],...
          'foregroundcolor',[0 0 0 0],...
          'fontsize',25,...
          'String','Grupa: 2125');
      
      
 uicontrol('Style','pushbutton',...
             'Units','normalized',...
             'Position',[0.89 0.015 0.1 0.06],...
             'FontWeight','bold',...
             'FontSize',13,...
             'String','Inchidere',...
             'Callback','close;');
